import React, { useState, useEffect } from 'react';
import Joyride, { Step, CallBackProps, STATUS } from 'react-joyride';
import { useAuth } from '@/contexts/AuthContext';

interface ProductTourProps {
  isVisible: boolean;
  onComplete: () => void;
  ideasCount: number;
  isLoading: boolean;
}

export const ProductTour: React.FC<ProductTourProps> = ({
  isVisible,
  onComplete,
  ideasCount,
  isLoading
}) => {
  const { user } = useAuth();
  const [run, setRun] = useState(false);

  useEffect(() => {
    console.log('🔍 DEBUG: ProductTour useEffect:', { isVisible, ideasCount, run });
    
    // Start tour when visible and no ideas are loaded yet
    if (isVisible && ideasCount === 0) {
      console.log('🔍 DEBUG: Starting ProductTour');
      setRun(true);
    } else if (ideasCount > 0) {
      // Stop tour when ideas are loaded
      console.log('🔍 DEBUG: Stopping ProductTour - ideas loaded');
      setRun(false);
    }
  }, [isVisible, ideasCount]);

  // Add keyboard support for skipping tour
  useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      if (run && event.key === 'Escape') {
        console.log('🔍 DEBUG: Tour skipped via Escape key');
        setRun(false);
        onComplete();
      }
    };

    if (run) {
      document.addEventListener('keydown', handleKeyDown);
      return () => document.removeEventListener('keydown', handleKeyDown);
    }
  }, [run, onComplete]);

  const steps: Step[] = [
    {
      target: 'body',
      content: (
        <div className="text-center">
          <h3 className="text-lg font-bold mb-2">Welcome to ID8! 🚀</h3>
          <p className="text-sm">
            We're generating your first personalized business ideas based on your profile.
            This may take a minute, so let's explore what you can do while you wait!
          </p>
        </div>
      ),
      placement: 'center',
      disableBeacon: true,
    },
    {
      target: '[data-tour="trending-repos"]',
      content: (
        <div>
          <h4 className="font-semibold mb-2">Trending Repositories as Starting Points</h4>
          <p className="text-sm">
            These are the latest trending repositories from GitHub that we use as inspiration:
            <br />• <strong>Real-time Data:</strong> Fresh trending repos updated daily
            <br />• <strong>Rapid Prototyping:</strong> Leverage existing codebases to build faster
            <br />• <strong>Market Validation:</strong> Popular repos indicate market demand
            <br />• <strong>Innovation Catalyst:</strong> Transform trending tech into business opportunities
          </p>
        </div>
      ),
      placement: 'bottom',
    },
    {
      target: '[data-tour="sidebar"]',
      content: (
        <div>
          <h4 className="font-semibold mb-2">Navigation Sidebar</h4>
          <p className="text-sm">
            Use this sidebar to navigate between different views:
            <br />• <strong>Dashboard:</strong> Overview of all your ideas
            <br />• <strong>Workspace:</strong> Generate and manage ideas by repository
            <br />• <strong>Profile:</strong> Update your preferences and skills
          </p>
        </div>
      ),
      placement: 'right',
    },
    {
      target: '[data-tour="idea-cards"]',
      content: (
        <div>
          <h4 className="font-semibold mb-2">AI-Generated Business Ideas</h4>
          <p className="text-sm">
            Each idea is generated by analyzing trending repos and your profile:
            <br />• <strong>Title & Hook:</strong> The core business concept
            <br />• <strong>Score:</strong> How promising the idea is (1-10)
            <br />• <strong>Effort:</strong> How much work to build (1-10)
            <br />• <strong>Status:</strong> Current stage of development
            <br />• <strong>Repo Context:</strong> Based on trending repository analysis
          </p>
        </div>
      ),
      placement: 'bottom',
    },
    {
      target: '[data-tour="idea-actions"]',
      content: (
        <div>
          <h4 className="font-semibold mb-2">Idea Actions</h4>
          <p className="text-sm">
            Click on any idea card to:
            <br />• <strong>View Details:</strong> See full description and analysis
            <br />• <strong>Get Deep Dive:</strong> Generate detailed business analysis
            <br />• <strong>Change Status:</strong> Move ideas between stages
            <br />• <strong>Add to Shortlist:</strong> Save your favorites
          </p>
        </div>
      ),
      placement: 'top',
    },
    {
      target: '[data-tour="generate-ideas"]',
      content: (
        <div>
          <h4 className="font-semibold mb-2">Generate New Ideas</h4>
          <p className="text-sm">
            Create custom business ideas or validate your own:
            <br />• <strong>Choose Industry:</strong> Focus on specific sectors
            <br />• <strong>Select Business Model:</strong> SaaS, marketplace, etc.
            <br />• <strong>Add Context:</strong> Describe your specific interests
            <br />• <strong>Personalization:</strong> Ideas tailored to your skills
            <br />• <strong>Rapid Validation:</strong> Test ideas quickly with AI analysis
          </p>
        </div>
      ),
      placement: 'left',
    },
    {
      target: '[data-tour="deep-dive"]',
      content: (
        <div>
          <h4 className="font-semibold mb-2">Deep Dive Analysis</h4>
          <p className="text-sm">
            Get comprehensive business analysis for any idea:
            <br />• <strong>Product Clarity:</strong> MVP definition and validation
            <br />• <strong>Market Opportunity:</strong> Size, timing, and potential
            <br />• <strong>Strategic Moat:</strong> Competitive advantages
            <br />• <strong>Investor Scoring:</strong> Professional evaluation
            <br />• <strong>Execution Plan:</strong> Step-by-step roadmap to launch
          </p>
        </div>
      ),
      placement: 'top',
    },
    {
      target: '[data-tour="lens-switcher"]',
      content: (
        <div>
          <h4 className="font-semibold mb-2">Lens Switcher</h4>
          <p className="text-sm">
            Analyze ideas from different perspectives:
            <br />• <strong>Founder Lens:</strong> Focus on product and execution
            <br />• <strong>Investor Lens:</strong> Evaluate market and financial potential
            <br />• <strong>Customer Lens:</strong> Understand user needs and pain points
          </p>
        </div>
      ),
      placement: 'top',
    },
    {
      target: '[data-tour="investor-deck"]',
      content: (
        <div>
          <h4 className="font-semibold mb-2">Investor Deck Exporter</h4>
          <p className="text-sm">
            Generate a professional investor presentation in seconds:
            <br />• <strong>AI-Generated Content:</strong> Slides created from your idea data
            <br />• <strong>Customizable Templates:</strong> Choose what to include
            <br />• <strong>Export to PDF:</strong> Ready to share with investors
          </p>
        </div>
      ),
      placement: 'top',
    },
    {
      target: '[data-tour="collaboration"]',
      content: (
        <div>
          <h4 className="font-semibold mb-2">Collaborate on Ideas</h4>
          <p className="text-sm">
            Work with your team to build the next big thing:
            <br />• <strong>Invite Collaborators:</strong> Add team members as editors or viewers
            <br />• <strong>Propose Changes:</strong> Editors can suggest edits to an idea
            <br />• <strong>Approve & Reject:</strong> Owners can review and merge changes
            <br />• <strong>Leave Comments:</strong> Give and get feedback
          </p>
        </div>
      ),
      placement: 'top',
    },
    {
      target: '[data-tour="profile"]',
      content: (
        <div>
          <h4 className="font-semibold mb-2">Personalize Your Experience</h4>
          <p className="text-sm">
            Update your profile to get better ideas:
            <br />• <strong>Skills & Experience:</strong> What you're good at
            <br />• <strong>Interests & Goals:</strong> What you want to build
            <br />• <strong>Business Preferences:</strong> Industries and models
            <br />• <strong>Risk Tolerance:</strong> How ambitious you want to be
          </p>
        </div>
      ),
      placement: 'bottom',
    },
    {
      target: 'body',
      content: (
        <div className="text-center">
          <h3 className="text-lg font-bold mb-2">You're All Set! 🎉</h3>
          <p className="text-sm">
            Your ideas should be appearing now! Start exploring and don't hesitate to:
            <br />• Generate more ideas with different parameters
            <br />• Request deep dives on promising concepts
            <br />• Update your profile for better personalization
            <br />• Save your favorites to your shortlist
            <br />• Use trending repos as inspiration for rapid prototyping
          </p>
          <p className="text-xs mt-2 text-gray-600">
            You can always access help and tips from the sidebar menu.
          </p>
        </div>
      ),
      placement: 'center',
    },
  ];

  const handleCallback = (data: CallBackProps) => {
    const { status } = data;
    
    if (status === STATUS.FINISHED || status === STATUS.SKIPPED) {
      setRun(false);
      onComplete();
    }
  };

  if (!run) return null;

  return (
    <Joyride
      steps={steps}
      run={run}
      continuous={true}
      showProgress={true}
      showSkipButton={true}
      hideCloseButton={false}
      disableOverlayClose={false}
      callback={handleCallback}
      styles={{
        options: {
          primaryColor: '#3b82f6',
          zIndex: 10000,
        },
        tooltip: {
          backgroundColor: '#ffffff',
          borderRadius: '8px',
          boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
          padding: '16px',
          maxWidth: '400px',
        },
        tooltipTitle: {
          color: '#1f2937',
          fontSize: '16px',
          fontWeight: '600',
        },
        tooltipContent: {
          color: '#4b5563',
          fontSize: '14px',
          lineHeight: '1.5',
        },
        buttonNext: {
          backgroundColor: '#3b82f6',
          borderRadius: '6px',
          padding: '8px 16px',
          fontSize: '14px',
          fontWeight: '500',
        },
        buttonBack: {
          color: '#6b7280',
          marginRight: '8px',
        },
        buttonSkip: {
          color: '#6b7280',
          fontSize: '14px',
          fontWeight: '500',
          textDecoration: 'underline',
          cursor: 'pointer',
        },
        buttonClose: {
          display: 'block',
          position: 'absolute',
          top: '8px',
          right: '8px',
          background: 'none',
          border: 'none',
          fontSize: '18px',
          cursor: 'pointer',
          color: '#6b7280',
          padding: '4px',
          borderRadius: '4px',
        },
        overlay: {
          backgroundColor: 'rgba(0, 0, 0, 0.5)',
        },
        spotlight: {
          backgroundColor: 'transparent',
        },
      }}
      locale={{
        back: 'Back',
        close: 'Close',
        last: 'Finish',
        next: 'Next',
        skip: 'Skip Tour',
      }}
    />
  );
}; 